### ISSUE TITLE
Error 2113703873

### ISSUE THREAD

**Issue by francoismarais** [onepub-dev/onepub#533] opened 2024-03-24 15:57 UTC
**Describe the bug**
When trying to invite a member or contact support I receive an error message 

"Bloody hell
Fumbledig; An Error occurred.
Please quote 2113703873 when reporting this error.
Clearing your browser cache may help."

**To Reproduce**
1. Go to onepub.dev
2. Click on 'invite'
3. Click invite collaborator
4. Fill in name and email
5. Tick all boxes and hit next
6. Click Next 
7. Click Send
8. See Error

**Expected behavior**
Send the email to the invited user

**Screenshots**
![image](https://github.com/onepub-dev/onepub/assets/3921915/37ad3a50-df08-4537-8540-9cfc47ad2183)

**Desktop (please complete the following information):**
 - Browser Edge

**Additional context**
Problem exists with contacting support too.

**Comment by bsutton** [comment] 2024-03-24 22:04
Maris can you send an email to support@onepub.dev with the email address you entered into the invite screen as well as confirming that you were trying to email from the account attached to francois.andrew.marais@gmail.com?

**Comment by bsutton** [comment] 2024-03-24 22:05
Also what do you mean by:

Problem exists with contacting support too.

**Comment by bsutton** [comment] 2024-03-24 22:46
Francois,
so the root cause was that the email confirmation to your email address failed. There was then a secondary error (a bug on our end) that caused the error you saw.

We have a fix in hand for the secondary issue and will deploy it later today.

Can you confirm that the email address 'francois.andrew.marais@gmail.com' is correct. This is the email address that our system tried to send to.

**Comment by francoismarais** [comment] 2024-03-25 04:57
> Also what do you mean by:
> 
> Problem exists with contacting support too.

![image](https://github.com/onepub-dev/onepub/assets/3921915/6a4062ec-0a55-4703-8c7e-63c249ddf4bb)


When using the contact OnePub form the same error is received. 

![image](https://github.com/onepub-dev/onepub/assets/3921915/74cda467-efee-4e7f-85b9-05e4075f1bb3)

**Comment by francoismarais** [comment] 2024-03-25 05:01
> Francois, so the root cause was that the email confirmation to your email address failed. There was then a secondary error (a bug on our end) that caused the error you saw.
> 
> We have a fix in hand for the secondary issue and will deploy it later today.
> 
> Can you confirm that the email address '[francois.andrew.marais@gmail.com](mailto:francois.andrew.marais@gmail.com)' is correct. This is the email address that our system tried to send to.

I was trying to invite joshgilliver.dev@gmail.com, using my account francois.andrew.marais@gmail.com. and visa versa.

**Comment by bsutton** [comment] 2024-03-25 05:54
Francois,
we have found the root cause.

We use google as an smtp provider and according to their support staff they
changed their configuration requirements - without notice.
I'm still skeptical that their support team has given us the correct
information ( I doubt that google would have made a change without
notification) but we are changing the configuration  and should have the
problem resolved shortly.

Apologies for the pain.

I will email once the fix has been applied.

Brett

**Comment by bsutton** [comment] 2024-03-25 06:06
Francois,
looks like the problem has now been resolved.

Give it a try and let me know if you have any issues.

Brett

**Comment by francoismarais** [comment] 2024-03-25 06:30
Thank you the issue looks like it's resolved. Thank you @bsutton

**Closed** 2024-03-25 06:30 UTC
