### ISSUE TITLE
Cannot login via CLI

### ISSUE THREAD

**Issue by jakeBrightHR** [onepub-dev/onepub#529] opened 2023-10-31 13:46 UTC
**Describe the bug**
I cannot login to OnePub via the CLI.

**To Reproduce**
1. Type `onepub login` into the terminal
2. Paste in the login url into browser (Tested with Chrome and Safari)
3. The login page loads and a white box with a Retry button appears
4. Cannot do anything else. The user is not logged in

**Expected behavior**
I should be able to login once pasting in the login url into my browser.

**Screenshots**
![Screenshot 2023-10-31 at 13 37 49 (1)](https://github.com/onepub-dev/onepub/assets/112476079/d916f28a-024c-4ee8-b6d7-ddd6d3763f58)

** Problems with CLI tooling **
If your issue is with the OnePub CLI tooling then:

Run onepub doctor and post the output here:

```
BRI52344L :: ~ » onepub doctor                                                                 
OnePub version: 4.0.0
Platform
Dart version:  3.1.5
Dart path:   /Users/asama.shahbaz/Documents/flut
OS:       macos
OS version:   Version 14.1 (Build 23B74)
Locale:     en-GB
Path separator: /
URLs
Web site:    https://onepub.dev/
API endpoint:  https://onepub.dev/api/Organisation
Environment
Pub Cache:   /<HOME>/.pub-cache
PUB_CACHE:   not set and not used.
PATH:
        /opt/homebrew/bin
        /opt/homebrew/sbin
        /usr/local/bin
        /System/Cryptexes/App/usr/bin
        /usr/bin
        /bin
        /usr/sbin
        /sbin
        /var/run/com.apple.security.cryptex ERROR: path does not exist.
        /var/run/com.apple.security.cryptex ERROR: path does not exist.
        /var/run/com.apple.security.cryptex ERROR: path does not exist.
        /<HOME>/Documents/flutter/bin
        /<HOME>/Documents/flutter/bin
        /<HOME>/.pub-cache/bin
Shell Settings
$SHELL:     /bin/zsh
Detected:    zsh
Start script:  /<HOME>/.zshrc
Repository tokens
Not logged into OnePub.
Status
You are not logged into OnePub.
run: onepub login
checking status...
OnePub: status healthy.
Server Version: 4.45.28
```

**Desktop (please complete the following information):**
 - OS: MacOS Version 14.1 (Build 23B74)
 - Browser: Chrome, Safari

**Comment by bsutton** [comment] 2023-10-31 21:18
What user name were you attempting to login.

**Comment by bsutton** [comment] 2023-10-31 22:47
Just an update to let you know we have identified the problem and are in the process of pushing a fix.

We had a race condition in the load where we tried to trigger the auth scripts before they had been loaded.

Not quite clear as to why it started appearing just now so will do further investigation, but the root cause has been resolved.

Apologies for the inconvenience.

Will post a final update once the update has been pushed .

**Comment by bsutton** [comment] 2023-10-31 23:05
Kim,
we are pushing a fix. It should be available within the next 30 mins.

**Comment by bsutton** [comment] 2023-10-31 23:06
FYI, you can get around the problem for the moment by:

Login to onepub from the web.
Go to My OnePub |Member
find your user.
export the your token.
From the cli run:

onepub import --ask

paste the token.

You are now logged in.

**Comment by bsutton** [comment] 2023-10-31 23:23
So the problem has now been resolved and you should be able to login to onepub from the cli.

It looks like we were experiencing higher-than-normal latency from our identity provider which triggered a race condition in our cli auth code.
This was a bug in our code which has now been fixed.

Apologies for the inflicted pain. 

I'm closing this issue out but if you have any issues please don't hesitate to re-open the issue.

**Closed by bsutton** 2023-10-31 23:23 UTC
